### ISSUE TITLE
Light Bulb Does not Behave Correctly With Field Lines on iPad 3 iOS 9

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/faradays-law#69] opened 2015-10-27 17:16 UTC
Test device: iPad 3, Disessa

Operating System: iOS 9.0.2

Browser: Safari

Problem description: When the field lines are displayed, the light bulb does not behave correctly. It either does not light up or will be very bright and not go back down. I retested other platforms, including iPad 2 w/ iOS 8 and iOS9, and this behavior is not reproducible on those. 

Steps to reproduce: Open sim. Select to display field lines. Move magnet through coils.

Severity:

Screenshots: 
https://drive.google.com/file/d/0B_TAL-jnJOoKVEY5YVdzMWswcjA/view?usp=sharing 

Troubleshooting information (do not edit):
Name: ‪Faraday's Law‬
URL: http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.0-rc.1/faradays-law_en.html
Version: 1.1.0-rc.1 2015-10-21 22:21:53 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 9_0_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A452 Safari/601.1
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"HEAD"},"axon":{"sha":"e2237347","branch":"HEAD"},"babel":{"sha":"40d73ff6","branch":"master"},"brand":{"sha":"8a756e53","branch":"HEAD"},"chipper":{"sha":"157b9cf3","branch":"HEAD"},"dot":{"sha":"d99cbe46","branch":"HEAD"},"faradays-law":{"sha":"08f7de35","branch":"1.1"},"joist":{"sha":"121bb0de","branch":"HEAD"},"kite":{"sha":"40dc703a","branch":"HEAD"},"phet-core":{"sha":"e9f36af1","branch":"HEAD"},"phetcommon":{"sha":"0e4754fe","branch":"HEAD"},"scenery":{"sha":"2edf8a01","branch":"HEAD"},"scenery-phet":{"sha":"88ade507","branch":"HEAD"},"sherpa":{"sha":"1759eade","branch":"HEAD"},"sun":{"sha":"b66398a5","branch":"HEAD"},"tandem":{"sha":"c54f1082","branch":"HEAD"},"vibe":{"sha":"4b94a32b","branch":"HEAD"}}

**Comment by jbphet** [comment] 2015-10-27 20:16
Assigning to @ariel-phet for a decision on whether to work to address this issue.  He has said before that iPad 3 is no longer a supported platform.  I am able to duplicate this on Disessa (the iPad 3) and I can confirm that it does *not* occur on my iPad 2 running iOS8.  I'm not going to roll the next release candidate until we decide whether this is a blocking issue.

Also, I just showed this to @jonathanolson, and he thinks this may be a Scenery thing.

**Comment by jbphet** [comment] 2015-10-27 20:20
This issue does *not* exist with the currently published version of this sim.  Here's a somewhat durable link to this version (where the problem doesn't exist): http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.0.2/

And, for reference, here's a link to the current RC that exhibits this problem:
http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.0-rc.1/faradays-law_en.html

**Comment by ariel-phet** [comment] 2015-10-27 21:53
If it is a "Scenery thing" and did not exist before, it seems worth investigating. Would be good to at least identify what is causing the issue.

**Comment by pixelzoom** [comment] 2015-10-29 18:59
Dev meeting:  test on iOS 9.1.

**Comment by jbphet** [comment] 2015-10-29 22:59
I upgraded the iPad 3 (Disessa) to iOS 9.1 and the problem did *not* go away.

**Comment by jbphet** [comment] 2015-10-29 23:09
Tested this on an iPad 2 (Tycho) running iOS 9.0 and the problem does not occur.

**Comment by jonathanolson** [comment] 2015-10-30 03:23
Committed fix. If a DT was >= 0.1s, that animation frame didn't trigger a model step. During the magnet animation on iPad 3, it must be slow enough that DTs are always >= 0.1s. Since the magnet/lines were moved in the callback (not based on the model/view step), they moved, while the sim model didn't execute.

**Closed by jonathanolson** 2015-10-30 03:23 UTC
