### ISSUE TITLE
Magnet can go through coils when dragged quickly

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/faradays-law#195] opened 2020-10-29 20:53 UTC
**Test device**
Lenovo ThinkPad

**Operating System**
Windows 10

**Browser**
Firefox, Chrome

**Problem description**
This is for https://github.com/phetsims/QA/issues/568
With field lines on, quickly dragging the magnet back and forth can cause it to go through the coil. 
Also occurs in published. 

**Steps to reproduce**
1. Turn on field lines
2. Drag the magnet up and down with the cursor near the middle, making sure to hit both ends of the coil. 

**Visuals**
https://drive.google.com/file/d/1xUsYca_gaqdI79J92LCRVJvQUM34vLMG/view?usp=sharing

Slo-mo using my phone: 
https://drive.google.com/file/d/1G7gpFDpHz_oZiZui1BQlPtkwYqMobvFq/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Law‬
URL: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_en_phet.html
Version: 1.4.0-dev.65 2020-10-27 23:56:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Language: en-US
Window: 1728x858
Pixel Ratio: 2.2222222222222223/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by brooklynlash** [comment] 2020-10-30 15:39
I have noticed that it is easier to replicate using field lines and both coils but you can also replicate with a single coil or without field lines, it just occurs less frequently.

**Comment by KatieWoe** [comment] 2020-10-30 16:49
I think this is in published. so marking as deferred. @brooklynlash if it isn't in published, let me know.

**Comment by KatieWoe** [comment] 2020-10-30 23:04
Further note: I've been seeing this more while I test Lovelace (slower Chromebook) then when I was testing on iPad or on my Mac. So performance may play a part, or make it easier to reproduce.

**Comment by jbphet** [comment] 2020-11-11 19:08
This is related to an older issue that was addressed and closed a while back, but I just had to back out some of the changes for it in order to make sound and keyboard nav work correctly.  See #47.

**Comment by jbphet** [comment] 2020-12-01 00:27
I did some work on dragging due to a number of problems with the behavior and implementation.  I think this should now be fixed on master.  @KatieWoe - please have QA test this on the current master version.

**Comment by brooklynlash** [comment] 2020-12-01 16:55
Looks good on master for Windows 10.

**Comment by brooklynlash** [comment] 2020-12-03 20:51
Also looks good on 1.4 rc1

**Comment by KatieWoe** [comment] 2020-12-04 20:33
Closing. Will reopen if this shows up again on a slower device.

**Closed by KatieWoe** 2020-12-04 20:33 UTC
Labels: status:ready-for-qa, type:bug
