### ISSUE TITLE
Dragging magnet to pan around while zoomed in causes jittery movement

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#197] opened 2020-10-30 19:35 UTC
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 14.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/568. Fairly minor. Feel free to close if not an issue. Mostly seen on iPad/touch screen, but reproduced a bit on laptop.
When the sim is zoomed in, you can drag the magnet to the edge of the screen to pan around. As you do, the magnet jitters around quite a bit.

**Visuals**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/41024075/97749280-6708d680-1ab4-11eb-89c0-a9ecdf24a580.gif)

**Comment by jbphet** [comment] 2020-11-02 23:46
This seems like it may well be related to #198, so I'm assigning to @jessegreenberg to investigate.

**Comment by jessegreenberg** [comment] 2020-11-04 22:59
I think this can be improved. The panning that happens during keyboard drag is quite smooth and the panning during keyboard dragging, and trying to match more closely what is done there during mouse movement will be a first step.

**Comment by jessegreenberg** [comment] 2020-11-09 23:26
The magnet is translated with mouse/touch position, whenever they move. When we pan the screen, the entire simulation moves under the mouse. So it creates a situation where further mouse/touch movements will make the magnet jump to the pointer because the magnet has relatively moved away from the mouse - heres another capture that 

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/6396244/98608074-765c0100-22b8-11eb-8440-8cb1da44dabf.gif)

**Comment by jessegreenberg** [comment] 2020-11-10 23:09
I have been thinking about this one for a while and don't see a quick fix, this one will take some time. The problem is identified in https://github.com/phetsims/faradays-law/issues/197#issuecomment-724343268 - draggable things in PhET sims translate with mouse/touch movement. When we pan the entire simulation in this case, everything moves under the mouse, including the thing that is being dragged. When the mouse moves again it snaps the object to its new position. When done quickly, it looks jittery. This is not specific to faradays-law, it will happen for all draggables.

@emily-phet how important/offensive do you find this, and should we spend time now to improve this?

**Comment by emily-phet** [comment] 2020-11-22 04:18
@jessegreenberg I think this is ok to leave as is for this sim.

**Comment by jbphet** [comment] 2020-11-24 20:55
Marking as deferred based on @emily-phet's comment above, but leaving open so that it can be tracked and tested on a subsequent release.

**Comment by jessegreenberg** [comment] 2020-12-11 22:07
OK sounds good - this is going to be a problem for all sims not just in Faradays Law so I am going to move to scenery.

**Comment by jessegreenberg** [comment] 2020-12-11 22:40
Issue moved to [phetsims/scenery #1125](https://github.com/phetsims/scenery/issues/1125) via [**ZenHub**](https://www.zenhub.com/)

**Closed by jessegreenberg** 2020-12-11 22:40 UTC
Labels: priority:5-deferred, type:bug
