### ISSUE TITLE
Sound crackles when unmuted

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#192] opened 2020-10-28 22:34 UTC
**Test device**
MacBook Air
**Operating System**
10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/568.
If sound is being produced while the sim is muted, and is then unmuted, there is a crackle that plays for a second or so.
**Steps to reproduce**
1. Use `?speed=.1` to draw out the length of the sound and make this easier to reproduce
2. Move the magnet so you get a large voltage
3. While voltage is falling, use the mute button to mute and then unmute the sim sound

**Visuals**
https://drive.google.com/file/d/1qxdzSj0ycxYOPqHl9eX8OsUsc16x1gl6/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Law‬
URL: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_en_phet.html
Version: 1.4.0-dev.65 2020-10-27 23:56:15 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Language: en-US
Window: 1308x686
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by terracoda** [comment] 2020-10-30 12:14
Just adding that I notice a lot of crackling on iPhone 7 iOS 13.7

**Comment by brooklynlash** [comment] 2020-10-30 15:15
Sound crackles on Windows 10 Firefox even without slowing down the sound

**Comment by jbphet** [comment] 2020-11-24 21:29
I am able to duplicate the crackling using Chrome and Firefox on a Macbook Air, but I'm not able to duplicate it on my Win 10 Dell XPS using Chrome, Firefox, or Edge, so this appears to be a Mac-specific problem.

At least for me, the problem is basically impossible to replicate without slowing down the sim speed(using the `speed=0.1` query parameter).

@brooklynlash said:

> Sound crackles on Windows 10 Firefox even without slowing down the sound

I'm not able to duplicate this on my Win 10 device, and I'm wondering if she is hearing the pegging of the voltmeter and mistaking this for crackling.  @brooklynlash - can you please elaborate on the conditions under which you're hearing crackling on Win10+Firefox and supply a recording if possible?

**Comment by brooklynlash** [comment] 2020-11-24 22:13
@jbphet I honestly am unsure on where I heard the crackling, and I cannot replicate it on my Window's 10 device, so it must have been a temporary speaker issue on my end. Sorry for the confusion.

**Comment by jbphet** [comment] 2020-12-02 00:03
I think that this may be due to a lot of volume changes taking place due to the problem described in https://github.com/phetsims/tambo/issues/129, and Mac hardware doesn't deal with it as well as other devices.

I discussed this with @emily-phet today at our regular review meeting, and since it is nigh on impossible to reproduce this behavior at normal sim speeds, we're not going to work on it prior to the impending RC.  In fact, I will simply close this issue and plan to address the problem generally when I work on https://github.com/phetsims/tambo/issues/61 and https://github.com/phetsims/tambo/issues/129.

**Closed by jbphet** 2020-12-02 00:03 UTC
Labels: type:bug
