### ISSUE TITLE
Current/light bulb, and voltage sounds

### ISSUE THREAD

**Issue by emily-phet** [phetsims/faradays-law#165] opened 2020-08-03 18:46 UTC
@Ashton-Morris @jbphet 

Please see the following link (to a section of the design doc) for my notes re designs for FL. The first section are my notes directly to you both re tomorrow's meeting (including some requests for ideas / sounds for @Ashton-Morris), and just below that is a summary of what I took from reviewing the demo videos and meeting notes from 2018.
https://docs.google.com/document/d/1_npYspPwkY1zrEOTUF_ITzTEZ_Qlra2i__4wap7pzP0/edit#heading=h.izqpmmc70elq

**Comment by Ashton-Morris** [comment] 2020-08-03 21:27
I have created another example video showing a few ideas. Will cross post with our similar issue.

- I have a sine that fades in a saturated sine when the voltage meter is at 75% and above.
- I have two chords that play for positive and negative that are more similar to what Mike had in his example.
- I also show two different click sounds for when the voltage meter is at max.

[Video here.](https://drive.google.com/file/d/1VgmexOMw61LeE3eevu7xdrd7VpDXyzTU/view?usp=sharing)

**Comment by emily-phet** [comment] 2020-08-04 16:59
@Ashton-Morris Thanks!

A few thoughts on variants:
- I like the "smoothness" of the sine sound, and find this a relatively pleasant sine wave sound...but the second demo option is more "pleasant". Is there any way to find a sound that feels more like something between these two demos, where  the second demo sound sounds just a lit bit more synth-y? So it's loses a small amount of that recognizable-as-a-musical-instrument feel. If there's a way to try that out, I think it would be helpful. At the moment, I think the second demo sound is a good contender, and maybe this variant I'm proposing could be a little better. 
- For the click sounds, I like the demo at 0:54 seconds. For that demo, is there a single click sound played twice, or is the click sound different for a positive max and negative max. If there the same, can you create a variant so we can try with one click sound for positive max, and a slightly different click sound for negative max?

**Comment by jbphet** [comment] 2020-08-04 23:04
This issue is a duplicate of https://github.com/phetsims/faradays-law/issues/163.  I've copied the comments above into that issue and will now close that one.

**Closed by jbphet** 2020-08-04 23:04 UTC
Labels: meeting:sonification
