### ISSUE TITLE
Auto-slide for bar magnet not working as expected on Main

### ISSUE THREAD

**Issue by terracoda** [phetsims/faradays-law#226] opened 2023-12-22 12:10 UTC
Over in https://github.com/phetsims/faradays-electromagnetic-lab/issues/25, @pixelzoom and @terracoda both tested the auto-slide interaction of the bar magnet. It was behaving as expected in the published version for @terracoda, but was not behaving as expected on main for @pixelzoom.

The auto-slide behavior and alternative input for the bar magnet likely needs retesting before any maintenance releases of this sim.

The expected behavior is outlined in  https://github.com/phetsims/faradays-electromagnetic-lab/issues/25#issuecomment-1866831699

**Comment by terracoda** [comment] 2023-12-22 12:14
Leaving this issue unassigned, but mentioning @jessegreenberg and @zepumph in case this is a known issue, or if it relates to any general alt input work.

**Comment by pixelzoom** [comment] 2023-12-22 15:23
Specifically https://github.com/phetsims/faradays-electromagnetic-lab/issues/25#issuecomment-1866707381:

> ...  I have not figured out how to stop the auto-slide -- I tried space, return, tabbing away -- and this seems like a bug or oversight.

And @terracoda describes the correct behavior in https://github.com/phetsims/faradays-electromagnetic-lab/issues/25#issuecomment-1866831699.

> Leaving this issue unassigned, but mentioning @jessegreenberg and @zepumph in case this is a known issue, or if it relates to any general alt input work.

If we'd like to use this in FEL, then it needs to be fixed before I'll consider incorporating it there.  So assigning to @arouinfar @jessegreenberg and @zepumph to decided how to proceed.  High priority since FEL is nearly feature complete, and another form of alt input has been implemented for the bar magnet.

**Comment by pixelzoom** [comment] 2023-12-22 15:25
@jessegreenberg @zepumph I'd also be interested in where this behavior is implemented, how close it is to being generalized enough that it's usable elsewhere, and whether you think it can/should be moved to common code.

**Comment by jessegreenberg** [comment] 2023-12-22 18:13
Yes, I reproduced the issue on main. I found it was from the conversion to KeyboardListener, it is fixed by the above commit.

The implementation is in MagnetAutoSlideKeyboardListener.js. It is specific to faradays-law right now but it could be generalized if the same behavior is needed for another sim.

**Comment by pixelzoom** [comment] 2023-12-27 20:48
I verified that this is now working expected in main -- that is, as @terracoda described in https://github.com/phetsims/faradays-electromagnetic-lab/issues/25#issuecomment-1866831699.

Closing.

**Closed by pixelzoom** 2023-12-27 20:48 UTC
Labels: priority:2-high, status:blocks-sim-publication, dev:alt-input
