### ISSUE TITLE
Can't drag magnet with mouse immediately after grabbing or dragging with keyboard

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#201] opened 2020-11-03 23:16 UTC
This behavior can be seen on the recent dev version https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_en_phet.html.

If the keyboard navigation is used to move the magnet and then, while focus is still on the magnet (i.e. it is surrounded by the solid or dotted pink rectangle), the user tries to grab and drag the magnet, it doesn't work.  A sound is produced that seems to indicate that both a grab and release are occurring, and then the magnet doesn't move when dragged.  If a second attempt is made to drag the magnet, it works fine.

For the record, I just tried this same sequence on the live version of the Friction sim, which has keyboard nav, and this problem doesn't occur, so this is something unique to what is being done in Faraday's Law.

**Comment by jbphet** [comment] 2020-11-17 00:11
Actually, I was a bit mistaken in the original issue description above.  I said that the problem doesn't exist in the "Friction" sim, and that is true for the published version, but it's _not_ true for the version on master.  This would seem to imply that this is a general problem with the interaction between the keyboard and the mouse drag listeners.

**Comment by jbphet** [comment] 2020-11-17 00:40
Here is an animation of the sequence.  I'm using keyboard nav to grab the magnet, then I'm immediately switching to the mouse and trying to grab and move it, and it doesn't move.

![efac-sticky-2](https://user-images.githubusercontent.com/3082831/99325103-cac02d00-2832-11eb-8252-a4e24b1c8fd6.gif)

**Comment by jbphet** [comment] 2020-11-17 00:43
I did some investigation on this, and found that the `end` function in the drag listener is being called from `ParallelDOM.blur`.  See the stack trace below.  This is now out of my area of expertise, so I'm going to turn it over to @jessegreenberg to see if he can explain why this is happening now (it doesn't seem to happen in the published version of "Friction"), and if it can be prevented or removed.

![image](https://user-images.githubusercontent.com/3082831/99323992-8895ec00-2830-11eb-9357-e6673756b6b4.png)

**Comment by jbphet** [comment] 2020-11-17 22:34
This issue was discussed at the weekly meeting for a11y and Faraday's Law, and @emily-phet mentioned that @zepumph had been looking at related issues recently.  Also, I looked at the history of the code and it looks like it's mostly been done by @zepumph.  Reassigning to him.

**Comment by zepumph** [comment] 2020-11-18 00:05
Interrupting has been occurring on blur since https://github.com/phetsims/scenery/commit/8e83433aa10da141ed2bdc00d833cbf924df761e, and I don't think that this is inherently wrong to do. 

I can confirm that this issue is fixed when you comment out the interrupt line.

> I said that the problem doesn't exist in the "Friction" sim, and that is true for the published version, but it's not true for the version on master. 

I was able to reproduce this problem with friction, and with GFL ruler. I was not able to reproduce this with the BASE balloon, which also uses GrabDragInteraction. This is because the drag listener  in BASE is added to the parent of the grab drag interaction, so I don't consider this a fix, just a workaround. 

I created https://github.com/phetsims/scenery-phet/issues/643 as a general issue. @jbphet, if time is of the essence, and you need to get to publication before @jessegreenberg and I can discuss in one week. I would recommend trying to wrap the GrabDragInteraction in a container that get's the DragListener. I don't really recommend this workaround, but wanted to mention it as a possibility if we need to unblock this issue.

**Comment by jbphet** [comment] 2020-11-18 17:06
Thanks @zepumph.  We're hoping to move to an RC fairly soon on this one, but if you and @jessegreenberg can address this in a week, I think that will work out time wise.  I don't think I'll try the workaround you described, and will instead focus on getting all other open issues addressed.

I'll leave this open and assigned to me for follow-up.

**Comment by jbphet** [comment] 2020-12-01 20:53
The work done for https://github.com/phetsims/scenery-phet/issues/643 has made it possible to pick up the magnet right away with the mouse after focusing on it via keyboard navigation, so the primary issue is fixed.  The only problem is that the drop and pick-up sounds both play in this case when grabbed with the mouse (or a touch event) after keyboard control.  From the code's point of view, this makes sense, since the magnet is being dropped by keyboard nav and then picked up by the mouse.  However, it makes for a bit of a weird user interaction, so I'll see if there is something that can be done to prevent this.

**Comment by jbphet** [comment] 2020-12-01 23:11
@emily-phet and I discussed the issue about both the release and grab sounds playing when going from keyboard to mouse focus and we decided not to spend time on it.  It doesn't sound bad, and is quite subtle, and there are bigger fish to fry.

**Comment by muedli** [comment] 2020-12-03 17:51
Looks fixed in 1.4.0-rc.1, but I'll let @KatieWoe check the box.

**Comment by KatieWoe** [comment] 2020-12-04 23:29
I agree.

**Closed by KatieWoe** 2020-12-04 23:29 UTC
Labels: status:ready-for-qa, type:bug
